# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache:
  packages: true

r_packages:
  - covr
  - dplyr
  - tidyr
  - knitr
  - htmlwidgets

r_build_args: "--no-build-vignettes"

warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'
