# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

branches:
  only:
   - master

sources:
    - r-packages-precise
    packages:
    - r-base-dev	
    - r-recommended
    - pandoc

    
# cache local R libraries directory:
cache:
  directories:
    - ~/Rlib

install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'if(!"devtools" %in% rownames(installed.packages())) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'if(!"dplyr" %in% rownames(installed.packages())) { install.packages("dplyr", dependencies = TRUE) }'
  - Rscript -e 'if(!"htmlwidgets" %in% rownames(installed.packages())) { install.packages("htmlwidgets", dependencies = TRUE) }'
  - Rscript -e 'if(!"pisaR" %in% rownames(installed.packages())) { devtools::install_github("mortonanalytics/pisaR") }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'

# Build and check package
script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran

r_packages:
    - dplyr
    - htmlwidgets
    - shiny
    - shinyWidgets
    
# report coverage rate to coveralls
after_success:
  - Rscript -e 'covr::coveralls(exclusions = "src/RcppExports.cpp")'

# send e-mails if stuff changes
notifications:
  email:
    on_success: change
    on_failure: change